### ISSUE TITLE
Can i use this script to provide my hosting end users a free sub domain?

### ISSUE THREAD

**Issue by anantsparrow** [BlossomDNS/register#14]
Just wondering to provide free sub domains to my hosting clients

**Comment by JewishLewish** [comment]
Yes you can.

**Comment by DWAA1660** [comment]
yes, you can clone this project change the config to your domains etc and they can use this to get a subdomain of whatever domain you put into config

**Comment by anantsparrow** [comment]
Great thanks, is there any new features you guys have in mind to implement in this script for future updates?

**Comment by JewishLewish** [comment]
@anantsparrow Development on V2.0 is still happening. We're aiming on adding more features and/or fix potential bugs. Right now V1.0 is stable and operates as normal.

Refer to this -> [V2.0 Development](https://github.com/BlossomDNS/register/pull/6)

If interested, feel free to join the discord so we can talk over direct messages.

**Comment by anantsparrow** [comment]
> @anantsparrow Development on V2.0 is still happening. We're aiming on adding more features and/or fix potential bugs. Right now V1.0 is stable and operates as normal.
> 
> Refer to this -> [V2.0 Development](https://github.com/BlossomDNS/register/pull/6)
> 
> If interested, feel free to join the discord so we can talk over direct messages.

Sure! joined

**Comment by DWAA1660** [comment]
gong to close this feel free to reopen if you have more questions
